### ISSUE TITLE
求教华为p9关于导航栏的适配方案

### ISSUE THREAD

**Issue by weitto** [wildma/ScreenAdaptation#10]
华为P9是手动控制导航栏是否显示的。当导航栏隐藏的时候，适配方案是1080x1920的。在进入应用后，显示导航栏，再进入另一个界面，却又适配的另外的方案，导致界面差距太大。这样的情况如何解决呢？大佬

**Comment by wildma** [comment]
@weitto 使用我这种方案是不存在导航栏等问题的，因为适配的是最小宽度，即使导航栏、虚拟按键等变化影响的是高度，并不会影响宽度呢。
