### ISSUE TITLE
请问app 里面有的界面需要横屏显示 应该怎么去设置额？

### ISSUE THREAD

**Issue by i91h1r** [wildma/ScreenAdaptation#13]
xml布局都是按照横屏去写的，UI 给的 距屏幕 左边的dp值都有，设置成按照base_dp=375 生成的dimens 去设置  不对。应该怎么去弄？

**Comment by wildma** [comment]
如果设计图最小宽度是一样的，那么横竖屏都是一样的用法，设计图怎么给就怎么写。
