### ISSUE TITLE
不同横屏设备的适配

### ISSUE THREAD

**Issue by LjieQ** [wildma/ScreenAdaptation#15]
公司有两个设备，一台华为平板和一台RK3288的设备，分辨率分别为1920*1200、1366*768。
具体参数如下图：
1，华为平板：
![TIM截图20191210174708](https://user-images.githubusercontent.com/34932454/70518945-27708d80-1b76-11ea-9e69-d7dc89b6d0f0.png)
2，RK3288主板：
![TIM截图20191210174236](https://user-images.githubusercontent.com/34932454/70519000-33f4e600-1b76-11ea-9f98-f46d59c16664.png)
### 要如何才能同时适配两个不同分辨率的设备吗？
目前UI的给的设计图是按照1920*1200来设计的
1，通过PxCook来查看dp标注，使用xxhdpi下的标注，在华为平板（1920*1200）是能正常的显示。但是在RK3288主板(1366*768)上就显示不完全，宽高的比例都不对。如下图所示：
![TIM截图20191210183546](https://user-images.githubusercontent.com/34932454/70522430-1460bc00-1b7c-11ea-8fd3-9333a8115e01.png)
![TIM截图20191210183637](https://user-images.githubusercontent.com/34932454/70522444-19257000-1b7c-11ea-8f96-62f4e08fb3e6.png)
2，在screenMatch.properties中已经设置base_dp=600，match_dp=600,768
请问，还需要如何配置才能让Rk3288的主板才能适配适配起来吗？

**Comment by wildma** [comment]
match_dp=600,768 没错，base_dp 是设计图最小宽度，就看你 base_dp 是否正确了。
