### ISSUE TITLE
Android studio 4.0生成的文件夹里没有文件

### ISSUE THREAD

**Issue by CaiJinFu** [wildma/ScreenAdaptation#17]
插件提示成功，但是生成的values-sw320dp，这些文件里面都没有东西

**Comment by wildma** [comment]
@CaiJinFu AS 4.0 是可以正常使用的。

**Comment by CaiJinFu** [comment]
> @CaiJinFu AS 4.0 是可以正常使用的。

后来我发现问题所在了，就是如果使用了Alibaba Java Coding Guidelines（阿里代码规范）这个插件，那生成的文件夹里就会没有东西，把Alibaba Java Coding Guidelines这个插件去掉就会有

**Comment by wildma** [comment]
@CaiJinFu 应该不是这个插件导致的，我也装了这个插件，一样是可以正常使用的。

**Comment by wildma** [comment]
> > @CaiJinFu AS 4.0 是可以正常使用的。
> 
> 后来我发现问题所在了，就是如果使用了Alibaba Java Coding Guidelines（阿里代码规范）这个插件，那生成的文件夹里就会没有东西，把Alibaba Java Coding Guidelines这个插件去掉就会有

应该不是这个插件导致的，我也装了这个插件，一样是可以正常使用的。

**Comment by Artorialover** [comment]
我也是这个现象，把Alibaba Java Coding Guidelines这个插件禁用了就可以了

**Comment by wildma** [comment]
> 我也是这个现象，把Alibaba Java Coding Guidelines这个插件禁用了就可以了

不确定你的是什么影响的，我这边同样是 AS 4.0+ Alibaba Java Coding Guidelines 插件启用，是可以正常使用的。
