### ISSUE TITLE
手机横屏过来的时候还是读到竖屏时宽度对应的尺寸

### ISSUE THREAD

**Issue by shouPol** [wildma/ScreenAdaptation#18]
非常感谢大佬分享的这个屏幕适配方案，在手机全是竖屏的情况下效果非常好。但是当手机切换成横屏后，还是读取的是横屏时对应的尺寸，请问一下有什么方法可以读取到手机横屏时宽度对应的尺寸吗？

**Comment by wildma** [comment]
如果你要同时适配横竖屏，但是没有用我文章中的方案一，那获取的值就是一样的。关于同时适配横竖屏你可以看看文章中的 2 个方案。
