### ISSUE TITLE
AS4.1不兼容了，能适配一下吗，大佬

### ISSUE THREAD

**Issue by jiqianwen** [wildma/ScreenAdaptation#19]
AS4.1不兼容了，能适配一下吗，大佬

**Comment by weixiao666** [comment]
me too

**Comment by wildma** [comment]
@jiqianwen 这个不是插件的问题，而是 AS 4.1 插件存放的位置发生了改变导致的。

解决：
找到插件存放的位置，然后将插件删除，重启 AS，重新安装即可。插件存放的位置如下：
```
C:\Users\UserName\AppData\Roaming\Google\AndroidStudio4.1\plugins
```

**Comment by wildma** [comment]
@weixiao666 这个不是插件的问题，而是 AS 4.1 插件存放的位置发生了改变导致的。

解决：
找到插件存放的位置，然后将插件删除，重启 AS，重新安装即可。插件存放的位置如下：
```
C:\Users\UserName\AppData\Roaming\Google\AndroidStudio4.1\plugins
```

**Comment by jiqianwen** [comment]
> @weixiao666 这个不是插件的问题，而是 AS 4.1 插件存放的位置发生了改变导致的。
> 
> 解决：
> 找到插件存放的位置，然后将插件删除，重启 AS，重新安装即可。插件存放的位置如下：
> 
> ```
> C:\Users\UserName\AppData\Roaming\Google\AndroidStudio4.1\plugins
> ```

好的，多谢，我去试试

**Comment by jiqianwen** [comment]
> @weixiao666 这个不是插件的问题，而是 AS 4.1 插件存放的位置发生了改变导致的。
> 
> 解决：
> 找到插件存放的位置，然后将插件删除，重启 AS，重新安装即可。插件存放的位置如下：
> 
> ```
> C:\Users\UserName\AppData\Roaming\Google\AndroidStudio4.1\plugins
> ```

试过了，依旧不行，报错就是显示的插件不兼容，自动屏蔽了

**Comment by zhanglin666** [comment]
C:\Users\UserName\AppData\Roaming\Google\AndroidStudio4.1\plugins  这是androidstudio的安装目录下的插件文件夹吗   试了  不行啊

**Comment by wildma** [comment]
@weixiao666 我试过了可以的，可能你还需要在 AS 先卸载再安装，具体看我新写的文章 [Android Studio 4.1 问题记录](https://www.jianshu.com/p/6d8bba29a8bd)。新的兼容后的插件我晚点改了再上传上来。

**Comment by wildma** [comment]
@zhanglin666 我试过了可以的，可能你还需要在 AS 先卸载再安装，具体看我新写的文章 [Android Studio 4.1 问题记录](https://www.jianshu.com/p/6d8bba29a8bd)。新的兼容后的插件我晚点改了再上传上来。
