### ISSUE TITLE
其他尺寸适配

### ISSUE THREAD

**Issue by 594238813** [wildma/ScreenAdaptation#20]
看了你的博客 和 别人的问题 
https://github.com/wildma/ScreenAdaptation/issues/7#issuecomment-421542790
是不是 只要  修改 screenMatch.properties  文件    base_dp=375   （或者是其他效果图上  的 宽度）
然后把你项目里  默认values/dimens.xml    copy到我的工程  然后 用插件 生成就行了？

我建了一个的demo 是这样操作的   我运行了几个虚拟机  大都试了一下 没问题  

不知道我的操作 步骤 有没有问题   望大佬指点一下

**Comment by wildma** [comment]
@594238813 没有问题，最新的方案就是以设计图最小宽度（单位为 dp）作为基准值。那个问题是以前的方案。看最新的博客就可以了。

**Comment by wildma** [comment]
@594238813 没有问题，最新的方案就是以设计图最小宽度（单位为 dp）作为基准值。那个问题是以前的方案。看最新的博客就可以了。
