### ISSUE TITLE
作者有没有考虑做成一个远程依赖

### ISSUE THREAD

**Issue by 880634** [wildma/ScreenAdaptation#23]
如题，这样做的好处有两个：
1. 不用在项目中看到这些通配符适配的代码，降低项目的复杂度
2. 更新迭代的成本比较低，只需修改远程依赖的版本即可

**Comment by wildma** [comment]
@880634 
这个做成远程依赖不太合适，因为：
1. 每个项目的需求不一样，有些可能只需要适配手机，有些可能需要适配平板、TV、一体机等，这样需要的 dimens.xml 文件都是不一样的。
2. 即使只适配手机，但是有些人会觉得 APK 体积增大 100KB 也不能接受，需要去除无用的 dp 值。

所以，目前用插件的方式我认为是最灵活的。如果你不想在项目中看到这些通配符适配的代码，可以自己放到一个本地 module。
