### ISSUE TITLE
荣耀平板v6,sp14适配字体偏大（真实设备）,红米k30看起来正常

### ISSUE THREAD

**Issue by RamboMing** [wildma/ScreenAdaptation#24]
截图看起来两个设备适配都没有问题，但是实质在真机上看平板V6 字体要大好多
![honor-v6](https://user-images.githubusercontent.com/13159720/119615655-37dffb00-be32-11eb-998b-ecce17a71960.png)
![红米k30](https://user-images.githubusercontent.com/13159720/119616516-467ae200-be33-11eb-8e58-56c9a8da5d4e.png)
![真机对比](https://user-images.githubusercontent.com/13159720/119616751-8b067d80-be33-11eb-941b-41330ca0c588.jpg)

**Comment by wildma** [comment]
就是这种效果的，原理是等比缩放，同一套设计图用在手机和平板等比缩放后就是这样，如果想在平板上字体也显示小的，只能单独对平板出图。

可以再看一遍文章中说的这句话：“smallestWidth 限定符适配的效果是让不同分辨率和密度的设备上能达到以设计图等比缩放的适配，如果设备与设计图相差太大时并不能达到很好的适配效果，需要单独出图，其他屏幕适配方案也是一样的。”

**Comment by RamboMing** [comment]
哦，了解，谢谢
