### ISSUE TITLE
项目组件化后 如何处理 dimens.xml 文件？

### ISSUE THREAD

**Issue by RDSunhy** [wildma/ScreenAdaptation#26]
是直接把 dimens.xml 放在所有组件都引用的 common组件中 还是 所有module都需要一份？组件化的项目资源名字有前缀要求 每个module都放一份 资源名都一样。

**Comment by zhangwenxiang26** [comment]
我把所有的 dimens.xml 都放在 common组件中 ，看起来没啥问题

**Comment by wildma** [comment]
@RDSunhy 
只放在 common 组件中即可。
