### ISSUE TITLE
新的最小宽度尺寸 ：451.7647

### ISSUE THREAD

**Issue by zhangwenxiang26** [wildma/ScreenAdaptation#27]
HUAWEI NOH-AL00 Android 10

屏幕宽 -----> widthPixels =1152
屏幕高 -----> heightPixels =2376
屏幕density -----> density =2.55
屏幕widthDP -----> widthDP =451.7647
屏幕heightDP -----> heightDP =931.7647
屏幕smallestWidthDP -----> smallestWidthDP =451.7647

**Comment by wildma** [comment]
@zhangwenxiang26 
感谢提供，最近会抽时间更新一下。
