### ISSUE TITLE
您好，首先感谢您的开源，你的库对我们这些开发者帮助非常的大，不过我有些不太理解的地方，想请教下dp转px的问题，这个问题不是您的库的问题

### ISSUE THREAD

**Issue by ideal-train** [wildma/ScreenAdaptation#28]
出于我的技术水平问题，在看到您的文章后感觉您对适配方面的知识挺好的，就来问下dp转px的问题

比如说我在如下信息的屏幕上：
 屏幕的宽度（单位：px）: 1200
 屏幕的高度（单位：px）: 1600
 屏幕密度（单位：DPI）: 160
 屏幕密度density（DPI / (160像素/英寸)）: 1.0
 base_dp（width/density）: 1200.0
此时1dp=1px
我通过代码动态设置时用下面这个方法没什么问题：1200dp可以刚好充满屏幕
 /**
     * dp值转换成px值
     *
     * @param dpValue dp值
     * @return px值
     */
    public static int dp2px(Context context, final float dpValue) {
        final float density= context.getResources().getDisplayMetrics().density;
        return (int) (dpValue * density+ 0.5f);
    }
//---------------------------------------------------------------------------------------------------------
换设备
    屏幕的宽度（单位：px）: 1080
    屏幕的高度（单位：px）: 1920
    屏幕密度（单位：DPI）: 420
    屏幕密度density（DPI / (160像素/英寸)）: 2.625
    base_dp（width/density）: 411.42856

我通过代码动态设置时（用上面dp2px方法）此设备下的
1200dp=3150.5px 远远超出了这个屏幕1080的宽，此时其他的dp也不适用了，通过代码适配就显得有问题了

请问在通过代码动态设置进行适配时
1.这个dp转px 是否和base_dp有关？
2.还是和屏幕宽度比有关？

我现在用的是2，dp转px改成了：
 (dpValue * density+ 0.5f)*当前设备宽/base_dp屏幕宽度;

请问我这么做合理吗？

**Comment by wildma** [comment]
1. 无关
2. 无关

dp 转 px 只与屏幕密度有关。

你这里出现错误应该是你使用错误，dp2px() 方法的参数 dpValue 应该从 dimens 文件中获取，如下：
```java
        // 获取对应资源文件下的 dp 值
        float pxValue2 = getResources().getDimension(R.dimen.dp_360);
        // 将 px 值转换成 dp 值
        int dpValue = ConvertUtils.px2dp(this, pxValue2);
```
这个文章中有说的，你回去再仔细看看。

**Comment by wildma** [comment]
@ideal-train 
1. 无关
2. 无关

dp 转 px 只与屏幕密度有关。

你这里出现错误应该是你使用错误，dp2px() 方法的参数 dpValue 应该从 dimens 文件中获取，如下：
```java
// 获取对应资源文件下的 dp 值
float pxValue2 = getResources().getDimension(R.dimen.dp_360);
// 将 px 值转换成 dp 值
int dpValue = ConvertUtils.px2dp(this, pxValue2);
```
这个文章中有说的，你回去再仔细看看。

**Comment by ideal-train** [comment]
> @ideal-train
> 
> 1. 无关
> 2. 无关
> 
> dp 转 px 只与屏幕密度有关。
> 
> 你这里出现错误应该是你使用错误，dp2px() 方法的参数 dpValue 应该从 dimens 文件中获取，如下：
> 
> ```java
> // 获取对应资源文件下的 dp 值
> float pxValue2 = getResources().getDimension(R.dimen.dp_360);
> // 将 px 值转换成 dp 值
> int dpValue = ConvertUtils.px2dp(this, pxValue2);
> ```
> 
> 这个文章中有说的，你回去再仔细看看。

一下子明白了，谢谢帮助
