### ISSUE TITLE
IDEA 插件库的作者是您吗？Dolphin 版本上文件格式存在异常

### ISSUE THREAD

**Issue by Orange-Jun** [wildma/ScreenAdaptation#32]
IDEA 插件库的作者是您吗？Dolphin 版本上文件格式存在异常
![image](https://user-images.githubusercontent.com/42060663/202144561-25c0eff0-b9cb-47be-8c08-0bf1cc8b34c0.png)

**Comment by wildma** [comment]
> IDEA 插件库的作者是您吗？Dolphin 版本上文件格式存在异常 ![image](https://user-images.githubusercontent.com/42060663/202144561-25c0eff0-b9cb-47be-8c08-0bf1cc8b34c0.png)

请问存在什么异常呢？

**Comment by Orange-Jun** [comment]
> > IDEA 插件库的作者是您吗？Dolphin 版本上文件格式存在异常![图像](https://user-images.githubusercontent.com/42060663/202144561-25c0eff0-b9cb-47be-8c08-0bf1cc8b34c0.png)
> 
> 请问存在什么异常呢？

您好，从 Dolphin 以上的新版本 Android studio 会在生成 dimens.xml 文件中插入空行
可能是因为 idea 的变动造成的，不知道插件能不能修复一下
![image](https://github.com/wildma/ScreenAdaptation/assets/42060663/8e420e89-17f6-4278-a0ef-e8e41e90ff8d)
