### ISSUE TITLE
横屏怎么适配？

### ISSUE THREAD

**Issue by suzhonxia** [wildma/ScreenAdaptation#4]
应用如果是竖屏的情况下没问题，但如果屏幕旋转成横屏（如平板），则底部的按钮还是显示的是竖屏时的宽度.

**Comment by suzhonxia** [comment]
![Uploading Screenshot_2018-05-31-17-11-19-015_com.wildma.androidscreenadaptation.png…]()

**Comment by suzhonxia** [comment]
![screenshot_2018-05-31-17-11-09-289_com wildma androidscreenadaptation](https://user-images.githubusercontent.com/16772107/40773929-df42497c-64f6-11e8-95db-538a4b45b3d6.png)
![screenshot_2018-05-31-17-11-19-015_com wildma androidscreenadaptation](https://user-images.githubusercontent.com/16772107/40773932-e4a85a6e-64f6-11e8-8edb-ed5b8227af8b.png)

**Comment by wildma** [comment]
@suzhonxia 这个当然是了。你想下，假设宽度360dp，高度为640dp，难道相同分辨率，相同密度的手机你设置的360dp会变成640dp吗？屏幕适配的意思是你在不同分辨率和尺寸的手机上显示的效果是一样的，并不是说同样的手机你设置的360dp会变成640dp。px适配也是做不到的，你要实现竖屏占满宽度，换成横屏的时候也占满宽度的话可以使用match_parent或者权重之类的，或者你写2套布局分别是竖屏和横屏。
