### ISSUE TITLE
高度适配

### ISSUE THREAD

**Issue by 79660095** [wildma/ScreenAdaptation#5]
你好，这个是以720X1280的宽度基准来适配， 我测试好像高度好像不能完全适配。比如说720X1280的屏幕像华为的有些机子真实的屏幕高度并不是这个有虚拟导航栏，我设置高度为640dp 并不能兼容，能告知下这个是不兼容 还是智能用ScrollView 嵌套超出

**Comment by wildma** [comment]
兼容的。如果你的最小宽度dp为360dp，那么你这部华为的手机如果没有隐藏虚拟按键那高度就没有640dp，可能是604dp（每个手机的虚拟按键高度不一定相同）。所以你设置640dp是不对的，除非你隐藏虚拟按键，或者用ScrollView。但是你设置604dp就适配了，假如说你手机屏幕高度有640dp，然后你虚拟按键占了一半320dp，那么你还是设置640dp当然是不对的。

**Comment by wildma** [comment]
@79660095 兼容的。如果你的最小宽度dp为360dp，那么你这部华为的手机如果没有隐藏虚拟按键那高度就没有640dp，可能是604dp（每个手机的虚拟按键高度不一定相同）。所以你设置640dp是不对的，除非你隐藏虚拟按键，或者用ScrollView。但是你设置604dp就适配了，假如说你手机屏幕高度有640dp，然后你虚拟按键占了一半320dp，那么你还是设置640dp当然是不对的。
