### ISSUE TITLE
请问设计图是750*1334的设计图该怎么计算？

### ISSUE THREAD

**Issue by hardgit** [wildma/ScreenAdaptation#7]
请问设计图是750*1334的设计图该怎么计算？有解决方案吗？

**Comment by wildma** [comment]
@hardgit 
1. 计算出比例值 k=设计图的宽/360
2. 然后dp=设计图中标注的值/比例值
例如设计图的分辨率是750*1334，设计图上控件的宽高分别是100px，50px，则xml中就写宽dp_100/（750/360），高dp_50/（750/360）

**Comment by liguangze** [comment]
这个要自己计算吗，现在设计的基准尺寸是750*1334，我的手机打印的最小宽度是360，我只要把你的demo中的dimens拷进去，在生成相应的dimens文件就可以了吗，然后根据标注写了吗，但你你的demo是1280*720的，应该都一样吧，需要改什么地方吗

**Comment by liguangze** [comment]
屏幕最小宽度的，设计图的基准的屏幕最小宽度是怎么计算的，demo中为什么是360，
假如UI用的基准尺寸是750*1334，那么我的smallestWidth是多少，也是360吗，还是每个手机都不一样，那我应该用smallestWidth的作为基准

**Comment by showdy** [comment]
> @hardgit
> 
> 1. 计算出比例值 k=设计图的宽/360
> 2. 然后dp=设计图中标注的值/比例值
>    例如设计图的分辨率是750*1334，设计图上控件的宽高分别是100px，50px，则xml中就写宽dp_100/（750/360），高dp_50/（750/360）

这么计算太麻烦了，不能直接以 750 为基准吗，设计图100px，xml中就是写@px_100 这样子么
