### ISSUE TITLE
xml 字体适配没问题，动态设置适配不了

### ISSUE THREAD

**Issue by RamboMing** [wildma/ScreenAdaptation#8]
/*获取sp值*/
        float pxValue = getResources().getDimension(R.dimen.sp_15);//获取对应资源文件下的sp值
        int spValue = ConvertUtils.px2sp(this, pxValue);//将px值转换成sp值
        mTvShowParams.setTextSize(spValue);//设置文字大小

        /*获取dp值*/
        float pxValue2 = getResources().getDimension(R.dimen.dp_360);//获取对应资源文件下的dp值
        int dpValue = ConvertUtils.px2dp(this, pxValue2);//将px值转换成dp值

按照这个动态适配，字体显得很大，大神碰到过吗

**Comment by wildma** [comment]
@RamboMing 没有碰到过呢，你直接运行我的 Demo 看是否正常就知道了。
