### ISSUE TITLE
Huawei Mate 8-无法适配

### ISSUE THREAD

**Issue by a4425421** [wildma/ScreenAdaptation#9]

**Comment by a4425421** [comment]
mate8屏幕是1920x1080-6英寸的屏 -底部因为有个底部栏 -所以打印出来
heightPixels:1812
widthPixels:1080
density:2.5
heightDP:724.8
widthDP:432.0
按照教程他应该是在432dp，但是运行demo，他使用的还是360dp的。
如果我把432dp的dimen文件放到360dp的文件夹，mate8就可以正常显示，但是这样原本都是360dp的手机就都会适配不了。

请问这个应该如何解决,谢谢

**Comment by wildma** [comment]
@a4425421 如果是竖屏适配，那么按你打印的最小宽度就是432dp，系统会自动匹配values-sw432dp，没有该文件夹才会往下匹配。像你说的使用的是360dp的情况，可能是你的项目没有values-sw432dp往下匹配了，或者你哪里弄错了，你可以运行我的demo试试。
